name: glabella
version: "0.32"
license: "GPL-2.0-or-later"
date: 2021-03-13
description: |
    Low level interfaces to graph automorphism and canonical labelling tools

authors:
    - name: Gábor P. Nagy
      url: https://algebra.math.bme.hu/nagy-gabor

maintainers:
    - name: Gábor P. Nagy
      url: https://algebra.math.bme.hu/nagy-gabor

GAP: ">= 4.10"

www: https://nagygp.github.io/glabella/
readme: README.md
packageinfo: https://nagygp.github.io/glabella/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/nagygp/glabella/releases/download/v0.32/glabella-0.32.tar.gz

abstract: |
    The GAP package <strong>glabella</strong> provides a low level interface to softwares that can compute automorphisms, isomorphisms and canonical labellings of graphs. The graphs can be directed or undirected, and a vertex colouring can be specified. In the present version, the package provides interfaces to the programs <em>bliss, nauty</em> and </em>Traces.</em>

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    bliss, nauty, traces, graph isomorphism, canonical labelling, automorphism group.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Nag21</span>]   <b class='BibAuthor'>Nagy, G. P.</b>,
     <i class='BibTitle'>glabella, Low level interfaces to graph automorphism and canonical labelling tools,
             Version 0.32</i>
     (<span class='BibYear'>2021</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://nagygp.github.io/glabella/">https://nagygp.github.io/glabella/</a></span>.
    </p>
    

bibtex: |
    @misc{ glabella0.32,
      author =           {Nagy, G. P.},
      title =            {{glabella}, Low level interfaces to graph automorphism and canonical labelling tools, {V}ersion 0.32},
      month =            {Mar},
      year =             {2021},
      note =             {GAP package},
      howpublished =     {\href {https://nagygp.github.io/glabella/} {\texttt{https://nagygp.github.io/}\discretionary {}{}{}\texttt{glabella/}}},
      keywords =         {bliss; nauty; traces; graph isomorphism; canonical labelling; automorphism group},
      printedkey =       {Nag21}
    }

