name: glabella
version: "0.31"
license: "GPL-2.0-or-later"
date: 2021-03-04
description: |
    Low level interfaces to graph automorphism and canonical labelling tools

authors:
    - name: Gábor P. Nagy
      url: https://algebra.math.bme.hu/nagy-gabor

maintainers:
    - name: Gábor P. Nagy
      url: https://algebra.math.bme.hu/nagy-gabor

GAP: ">= 4.10"

www: https://nagygp.github.io/glabella/
readme: README.md
packageinfo: https://nagygp.github.io/glabella/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/nagygp/glabella/releases/download/v0.31/glabella-0.31.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    bliss, nauty, graph isomorphism, canonical labelling, automorphism group.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Nag21</span>]   <b class='BibAuthor'>Nagy, G. P.</b>,
     <i class='BibTitle'>glabella, Low level interfaces to graph automorphism and canonical labelling tools,
             Version 0.31</i>
     (<span class='BibYear'>2021</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://nagygp.github.io/glabella/">https://nagygp.github.io/glabella/</a></span>.
    </p>
    

bibtex: |
    @misc{ glabella0.31,
      author =           {Nagy, G. P.},
      title =            {{glabella}, Low level interfaces to graph automorphism
                          and canonical labelling tools, {V}ersion 0.31},
      month =            {Mar},
      year =             {2021},
      note =             {GAP package},
      howpublished =     {\href             {https://nagygp.github.io/glabella/}
                          {\texttt{https://nagygp.github.io/}\discretionary
                          {}{}{}\texttt{glabella/}}},
      keywords =         {bliss;  nauty; graph isomorphism; canonical labelling;
                          automorphism group},
      printedkey =       {Nag21}
    }

